# FROM python:3.7.7-alpine

# COPY . /app
# WORKDIR /app

# RUN apk --no-cache --update-cache add g++ linux-headers gcc musl-dev jpeg-dev zlib-dev libjpeg libressl-dev libffi-dev python3-dev openssl-dev \
#     && pip install setuptools wheel \
#     && pip install numpy pyyaml

# RUN pip install -r requirements.txt

# ENTRYPOINT ["python"]
# CMD ["app.py"]

FROM pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime

COPY . /app
WORKDIR /app

RUN pip install flask flask_restful werkzeug

CMD ["python", "app.py"]

# ENTRYPOINT ["python"]
# CMD ["python","app.py"]

# FROM ubuntu:20.04

# COPY . /app
# WORKDIR /app

# RUN apt-get update -y && apt-get install -y python3 python3-pip python3-dev python3-numpy \
#     && pip3 install --upgrade pip \
#     && python3 -V && pip3 -V \
#     && pip install -r requirements.txt \
#     && apt-get autoremove && apt-get autoclean

# ENTRYPOINT ["python"]
# CMD ["app.py"]